FROM node:20-alpine

WORKDIR /app

# Download and install the standalone Tailwind CLI
RUN wget https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -O /usr/local/bin/tailwindcss && \
    chmod +x /usr/local/bin/tailwindcss

CMD ["tailwindcss", "-i", "./static/src/input.css", "-o", "./static/dist/output.css", "--watch"]
