#!/bin/bash

set -e

if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit 1
fi

echo "Building image..."
docker build -t mexer .

echo "Creating Docker network..."
if ! docker network inspect mexerNetwork >/dev/null 2>&1; then
  docker network create mexerNetwork
fi

echo "Starting PostgreSQL Docker container..."
docker rm -f postgres 2>/dev/null || true # try to remove already running container
docker run -d --name postgres -p 5432:5432 \
  -e POSTGRES_USER=postgres \
  -e POSTGRES_PASSWORD=postgres \
  -v $(pwd)/postgres/mexer_schema.sql:/docker-entrypoint-initdb.d/mexer_schema.sql \
  --network mexerNetwork \
  postgres

echo "Waiting for PostgreSQL to be ready..."
until docker exec postgres pg_isready -U postgres >/dev/null 2>&1; do
  sleep 1
done

echo "Starting Mexer Docker container..."
docker rm -f mexer 2>/dev/null
docker run --name mexer -dp 8000:8000 \
  --env-file .env \
  -v /usr/share/dict/words:/usr/share/dict/words \
  -v $(pwd)/Mexer_site:/app:rw \
  --network mexerNetwork \
  mexer python3 manage.py debug 0.0.0.0:8000

echo "Running Migrations..."
docker exec mexer python3 manage.py migrate

echo "Inserting test data..."
psql postgresql://postgres:postgres@localhost -f postgres/insert_test_data.sql

echo "Creating superuser..."
docker exec -it mexer bash -c 'python3 manage.py createsuperuser --noinput \
  --username "$DJANGO_SUPERUSER_USERNAME" --email "$DJANGO_SUPERUSER_EMAIL"'