# Generated by Django 5.1.2 on 2025-01-30 15:51

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggEtaPFU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dataset', models.PositiveSmallIntegerField()),
                ('ValidFromVersion', models.PositiveSmallIntegerField()),
                ('ValidToVersion', models.PositiveSmallIntegerField()),
                ('Country', models.PositiveSmallIntegerField()),
                ('Method', models.PositiveSmallIntegerField()),
                ('EnergyType', models.PositiveSmallIntegerField()),
                ('LastStage', models.PositiveSmallIntegerField()),
                ('IncludesNEU', models.PositiveSmallIntegerField()),
                ('Year', models.PositiveSmallIntegerField()),
                ('ChoppedMat', models.PositiveSmallIntegerField()),
                ('ChoppedVar', models.PositiveSmallIntegerField()),
                ('ProductAggregation', models.PositiveSmallIntegerField()),
                ('IndustryAggregation', models.PositiveSmallIntegerField()),
                ('GrossNet', models.PositiveSmallIntegerField()),
                ('EXp', models.FloatField()),
                ('EXf', models.FloatField()),
                ('EXu', models.FloatField()),
                ('etapf', models.FloatField()),
                ('etafu', models.FloatField()),
                ('etapu', models.FloatField()),
            ],
            options={
                'db_table': 'AggEtaPFU',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AggLevel',
            fields=[
                ('AggLevelID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('AggLevel', models.TextField()),
                ('FullName', models.TextField()),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'AggLevel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('CountryID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('Country', models.TextField()),
                ('FullName', models.TextField()),
                ('Description', models.TextField()),
                ('IsCountry', models.BooleanField()),
                ('IsAggregation', models.BooleanField()),
                ('IsContinent', models.BooleanField()),
            ],
            options={
                'db_table': 'Country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('DatasetID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('Dataset', models.TextField()),
                ('Public', models.BooleanField()),
                ('FullName', models.TextField()),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'Dataset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnergyType',
            fields=[
                ('EnergyTypeID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('EnergyType', models.TextField()),
                ('FullName', models.TextField()),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'EnergyType',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrossNet',
            fields=[
                ('GrossNetID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('GrossNet', models.TextField()),
                ('FullName', models.TextField()),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'GrossNet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IEAData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'IEAData',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncludesNEU',
            fields=[
                ('IncludesNEUID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('IncludesNEU', models.BooleanField()),
                ('FullName', models.TextField()),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'IncludesNEU',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('IndexID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('Index', models.TextField()),
                ('Order', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'Index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LastStage',
            fields=[
                ('ECCStageID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('ECCStage', models.TextField()),
                ('FullName', models.TextField()),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'ECCStage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='matname',
            fields=[
                ('matnameID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('matname', models.TextField()),
                ('FullName', models.TextField()),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'matname',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('MethodID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('Method', models.TextField()),
                ('FullName', models.TextField()),
                ('Description', models.TextField()),
            ],
            options={
                'db_table': 'Method',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PSUT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dataset', models.PositiveSmallIntegerField()),
                ('ValidToVersion', models.PositiveSmallIntegerField()),
                ('ValidFromVersion', models.PositiveSmallIntegerField()),
                ('Country', models.PositiveSmallIntegerField()),
                ('Method', models.PositiveSmallIntegerField()),
                ('EnergyType', models.PositiveSmallIntegerField()),
                ('LastStage', models.PositiveSmallIntegerField()),
                ('IncludesNEU', models.PositiveSmallIntegerField()),
                ('Year', models.PositiveSmallIntegerField()),
                ('ChoppedMat', models.PositiveSmallIntegerField()),
                ('ChoppedVar', models.PositiveSmallIntegerField()),
                ('ProductAggregation', models.PositiveSmallIntegerField()),
                ('IndustryAggregation', models.PositiveSmallIntegerField()),
                ('matname', models.PositiveSmallIntegerField()),
                ('i', models.PositiveSmallIntegerField()),
                ('j', models.PositiveSmallIntegerField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'PSUTReAllChopAllDsAllGrAll',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('VersionID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('Version', models.TextField()),
            ],
            options={
                'db_table': 'Version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('YearID', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('Year', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'Year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=255)),
                ('account_info', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='EvizUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('institution_type', models.CharField(choices=[('Academic', 'Academic'), ('Government', 'Government'), ('Industry', 'Industry'), ('Non-Profit', 'Non-Profit'), ('Other', 'Other')], default='Other', max_length=10)),
                ('institution_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PassResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mexer.evizuser')),
            ],
        ),
    ]
