# Generated by Django 5.1.2 on 2025-02-04 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mexer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailauthcode',
            name='account_info',
        ),
        migrations.AddField(
            model_name='emailauthcode',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Mexer.evizuser'),
            preserve_default=False,
        ),
    ]
