# Generated by Django 5.1.2 on 2025-06-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mexer', '0002_remove_emailauthcode_account_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('PapersID', models.AutoField(primary_key=True, serialize=False)),
                ('Authors', models.TextField()),
                ('Year', models.PositiveSmallIntegerField()),
                ('Title', models.TextField()),
                ('Journal', models.TextField()),
                ('Volume', models.TextField()),
                ('Number', models.TextField()),
                ('Pages', models.TextField()),
                ('doi', models.TextField()),
                ('url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'Paper',
                'managed': False,
            },
        ),
    ]
