# Generated by Django 5.1.2 on 2025-07-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mexer', '0003_paper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
