# Generated by Django 5.2.4 on 2025-07-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mexer', '0004_delete_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('PapersID', models.AutoField(primary_key=True, serialize=False)),
                ('Authors', models.TextField()),
                ('Year', models.PositiveSmallIntegerField()),
                ('Title', models.TextField()),
                ('Journal', models.TextField()),
                ('Volume', models.TextField()),
                ('Number', models.TextField()),
                ('Pages', models.TextField()),
                ('doi', models.TextField()),
                ('URL', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'Papers',
                'managed': False,
            },
        ),
    ]
