# Generated by Django 5.2.4 on 2025-07-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mexer', '0005_paper'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aggetapfu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='agglevel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='energytype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='grossnet',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ieadata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='includesneu',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='laststage',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='matname',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='psut',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'managed': True},
        ),
    ]
