# Generated by Django 5.2.6 on 2025-09-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mexer', '0007_alter_aggetapfu_options_alter_agglevel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailauthcode',
            name='id',
        ),
        migrations.RemoveField(
            model_name='passresetcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='emailauthcode',
            name='code',
            field=models.TextField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passresetcode',
            name='code',
            field=models.TextField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
